# Site settings
title: Epoxy Floor Job Sheets
email: forms@epoxyfloorexperts.org
description: >-
  Internal job sheet submission system for Epoxy Floor Experts employees.
baseurl: "/forms" # Changed from "/epoxy-job-sheets" to "/forms" for the new subdirectory
url: "https://epoxyfloorexperts.org" # Changed from GitHub Pages URL to your domain
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-minifier

# Jekyll Minifier
jekyll-minifier:
  compress_css: true
  compress_javascript: true
  exclude: ['*.xml', '*.json', '*.html']

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - FAVICON-INSTRUCTIONS.md
  - assets/js/generate-favicons.js

