# Site settings
title: Epoxy Floor Experts
email: info@epoxyfloorexperts.org
description: >-
  Epoxy Floor Experts - Professional epoxy flooring services for residential and commercial properties.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://epoxyfloorexperts.org" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

